package registry

import (
	"fmt"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
)

// awesome-gno, vendored.
//
// https://github.com/gnoverse/awesome-gno is the community's own answer to
// "what is being built on gno.land", and it holds the half of that answer this
// explorer cannot see: wallets, editors, language servers, SDKs, workshops.
// None of those are a realm, so none of them can ever appear in a chain index.
//
// It is a snapshot in a file rather than a fetch at request time, for the same
// reason the rest of this package is: a page that reads GitHub on every load is
// a page that is down when GitHub is, slow when GitHub is slow, and different
// for two readers a minute apart. The snapshot is generated by
// `make awesome` (cmd/awesome-sync), committed, and embedded at build time, and
// it carries the commit it came from and the day it was taken so the page can
// say how old it is instead of implying it is live.

// AwesomeLink is a link that appeared inside an entry's description, lifted out
// of the markdown. The frontend builds DOM and never interpolates HTML, so a
// description has to arrive as plain text with its links beside it rather than
// as markup the page would have to parse.
type AwesomeLink struct {
	Text string `json:"text"`
	URL  string `json:"url"`
}

// AwesomeEntry is one bullet.
type AwesomeEntry struct {
	Name string `json:"name"`
	URL  string `json:"url,omitempty"`
	// Description is the prose after the dash, with any inline markdown links
	// flattened to their text and collected into Links.
	Description string        `json:"description,omitempty"`
	Links       []AwesomeLink `json:"links,omitempty"`
	// Path is the gno.land realm this entry points at, when one of its links
	// names a realm and nothing but a realm. A link with a render argument
	// (`r/gnoland/blog:p/gno-debugger`) names a *page* of a realm rather than
	// the realm itself, and attributing it to `r/gnoland/blog` would file the
	// Gno debugger under the blog. Those are deliberately left pathless.
	Path string `json:"path,omitempty"`
	// Site is a page you can open and use: the entry's own URL when that is an
	// app rather than a repository, or the homepage the project's GitHub repo
	// declares. Verified to answer at generation time, because a card with a
	// picture of a 404 is worse than a card with no picture.
	//
	// This is what the explorer photographs. A realm is photographed from its
	// Path instead, through the chain's own gnoweb.
	Site string `json:"site,omitempty"`
	// SiteFrom records where Site came from, so a reader can tell a link the
	// community wrote from one this repo went and looked up.
	SiteFrom string `json:"site_from,omitempty"`
}

// Site provenance.
const (
	// SiteListed means the community list itself points at the app.
	SiteListed = "listed"
	// SiteRepoHomepage means the list points at a repository and the
	// repository declares this homepage. That is the project's own assertion
	// about where its app lives, which is why it is worth following; it is
	// recorded separately because it is not what the list said.
	SiteRepoHomepage = "repo-homepage"
)

// IsApp reports whether this entry is something you can open and look at.
//
// The whole point of the distinction: a language server, a JSON-RPC client
// library and a conference talk are all genuinely part of this ecosystem and
// none of them has a screenshot. Putting them in a grid of pictures produces a
// grid of grey rectangles, which reads as a broken page rather than as a list
// of libraries.
func (e AwesomeEntry) IsApp() bool { return e.Site != "" || e.Path != "" }

// AwesomeSection is one `##` heading and its bullets.
type AwesomeSection struct {
	Title   string         `json:"title"`
	Slug    string         `json:"slug"`
	Note    string         `json:"note,omitempty"`
	Entries []AwesomeEntry `json:"entries"`
	// Archived says the list itself has retired these entries. Set at load
	// from awesomeArchived rather than stored in the file: it is this repo's
	// reading of somebody else's document, and writing it into the generated
	// snapshot would make it look like the community asserted it.
	Archived bool `json:"archived,omitempty"`
}

// Awesome is the parsed snapshot.
type Awesome struct {
	Source   string           `json:"source"`
	Readme   string           `json:"readme"`
	Contrib  string           `json:"contributing"`
	Commit   string           `json:"commit"`
	Synced   string           `json:"synced"`
	Sections []AwesomeSection `json:"sections"`
}

// Count is how many entries the snapshot holds, across every section.
func (a *Awesome) Count() int {
	n := 0
	for _, s := range a.Sections {
		n += len(s.Entries)
	}
	return n
}

// Paths is every realm this list points at, deduplicated and sorted, which is
// what the API asks the store about.
func (a *Awesome) Paths() []string {
	seen := map[string]bool{}
	out := []string{}
	for _, s := range a.Sections {
		for _, e := range s.Entries {
			if e.Path != "" && !seen[e.Path] {
				seen[e.Path] = true
				out = append(out, e.Path)
			}
		}
	}
	sort.Strings(out)
	return out
}

// awesomeAppSections are the sections whose entries can be apps at all.
//
// A section-level rule rather than a per-entry guess, because the community
// already sorted their own list and disagreeing with them entry by entry is how
// a "Tutorials" link ends up in an app grid. Everything outside these is a
// repository, a document, a talk or a social account, and the page says how
// many there are rather than rendering them.
var awesomeAppSections = map[string]bool{
	"apps":           true,
	"community-apps": true,
	"tools":          true,
}

// IsAwesomeAppSection reports whether a section can hold apps. Exported for the
// generator, which has to know before it goes looking for one.
func IsAwesomeAppSection(slug string) bool { return awesomeAppSections[slug] }

// Apps returns every entry worth a picture, in list order.
func (a *Awesome) Apps() []AwesomeEntry {
	out := []AwesomeEntry{}
	for _, s := range a.Sections {
		if !awesomeAppSections[s.Slug] || s.Archived {
			continue
		}
		for _, e := range s.Entries {
			if e.IsApp() {
				out = append(out, e)
			}
		}
	}
	return out
}

// AwesomeGroup is a section reduced to its name and how much of it the app grid
// does not show.
type AwesomeGroup struct {
	Title string `json:"title"`
	Slug  string `json:"slug"`
	Count int    `json:"count"`
}

// Others counts what is on the list and is not an app, by section.
//
// Counted and named rather than rendered. An SDK, a language server and a
// conference talk have no screenshot, and a grid of pictures with grey holes in
// it reads as a broken page rather than as a list of libraries. Saying "39 more
// entries: SDKs, docs, talks" and linking to the list is the honest version of
// the same information, and it is one line instead of six screens.
func (a *Awesome) Others() []AwesomeGroup {
	out := []AwesomeGroup{}
	for _, s := range a.Sections {
		n := 0
		for _, e := range s.Entries {
			if !awesomeAppSections[s.Slug] || s.Archived || !e.IsApp() {
				n++
			}
		}
		if n > 0 {
			out = append(out, AwesomeGroup{Title: s.Title, Slug: s.Slug, Count: n})
		}
	}
	return out
}

// SiteHosts is every host the explorer may ask for a screenshot of.
//
// This is the allowlist, and it is derived rather than written down: the set of
// hosts is exactly the set the vendored list names, so it cannot drift from
// what the page actually renders, and an arbitrary ?url= is refused because it
// is not in a file somebody committed.
func (a *Awesome) SiteHosts() []string {
	seen := map[string]bool{}
	out := []string{}
	for _, e := range a.Apps() {
		if e.Site == "" {
			continue
		}
		u, err := url.Parse(e.Site)
		if err != nil {
			continue
		}
		h := strings.ToLower(u.Hostname())
		if h != "" && !seen[h] {
			seen[h] = true
			out = append(out, h)
		}
	}
	sort.Strings(out)
	return out
}

// AllowsSite reports whether a URL is one this explorer offers a picture of.
//
// Exact string match against the vendored list, not a host match: the host set
// is what gnoshot is configured with, and this is the tighter gate in front of
// it. A caller may ask for a screenshot of a page the community vouched for,
// and for nothing else on that host.
func (a *Awesome) AllowsSite(raw string) bool {
	for _, e := range a.Apps() {
		if e.Site != "" && e.Site == raw {
			return true
		}
	}
	return false
}

// awesomeArchived names the sections whose entries are explicitly no longer
// current. The list keeps them, and so do we, but a directory that mixed a
// retired testnet into the same grid as a live app would be worse than one that
// dropped them: the reader cannot tell, and the page is the only thing that
// could have told them.
var awesomeArchived = map[string]bool{"archive": true}

var (
	commitSHA = regexp.MustCompile(`^[0-9a-f]{40}$`)
	slugSafe  = regexp.MustCompile(`^[a-z0-9-]+$`)
)

func loadAwesome() (*Awesome, error) {
	var doc Awesome
	if err := readJSON("data/awesome.json", &doc); err != nil {
		return nil, err
	}
	if err := validateAwesome(&doc); err != nil {
		return nil, err
	}
	for i := range doc.Sections {
		doc.Sections[i].Archived = awesomeArchived[doc.Sections[i].Slug]
	}
	return &doc, nil
}

func validateAwesome(a *Awesome) error {
	switch {
	case strings.TrimSpace(a.Source) == "":
		return fmt.Errorf("awesome.json: no source")
	case !commitSHA.MatchString(a.Commit):
		// The commit is what makes the snapshot checkable: without it a reader
		// cannot tell which version of the list they are looking at, and a
		// regenerated file is indistinguishable from an edited one.
		return fmt.Errorf("awesome.json: commit %q is not a full sha", a.Commit)
	case len(a.Sections) == 0:
		return fmt.Errorf("awesome.json: no sections")
	}
	if err := validateChecked("awesome.json", "snapshot", a.Synced); err != nil {
		return err
	}
	if a.Synced == "" {
		return fmt.Errorf("awesome.json: no synced date")
	}
	seenSlug := map[string]bool{}
	for _, s := range a.Sections {
		switch {
		case strings.TrimSpace(s.Title) == "":
			return fmt.Errorf("awesome.json: a section has no title")
		case !slugSafe.MatchString(s.Slug):
			return fmt.Errorf("awesome.json: %q has slug %q, want [a-z0-9-]+", s.Title, s.Slug)
		case seenSlug[s.Slug]:
			return fmt.Errorf("awesome.json: slug %q is used twice", s.Slug)
		case len(s.Entries) == 0:
			return fmt.Errorf("awesome.json: %q has no entries", s.Title)
		}
		seenSlug[s.Slug] = true
		for _, e := range s.Entries {
			if strings.TrimSpace(e.Name) == "" {
				return fmt.Errorf("awesome.json: %q holds an entry with no name", s.Title)
			}
			if e.Path != "" && !realmPath.MatchString(e.Path) {
				return fmt.Errorf("awesome.json: %s has path %q, which is not a gno.land path", e.Name, e.Path)
			}
			if e.Site != "" {
				u, err := url.Parse(e.Site)
				if err != nil || (u.Scheme != "https" && u.Scheme != "http") || u.Hostname() == "" {
					return fmt.Errorf("awesome.json: %s has site %q, which is not an http url", e.Name, e.Site)
				}
				// The explorer offers a screenshot of every site in here, so an
				// entry naming one without saying where it came from is an
				// unattributed claim that this project lives at that address.
				if e.SiteFrom != SiteListed && e.SiteFrom != SiteRepoHomepage {
					return fmt.Errorf("awesome.json: %s has site_from %q", e.Name, e.SiteFrom)
				}
			}
			if e.Path != "" && strings.Contains(e.Path, ":") {
				// Belt and braces: the parser already refuses these, and the
				// reason is worth failing loudly on rather than rediscovering.
				return fmt.Errorf("awesome.json: %s has path %q, which names a page and not a realm", e.Name, e.Path)
			}
		}
	}
	return nil
}

// SyncedAge is how many days old the snapshot is, for a page that would rather
// say "14 days ago" than print a date and leave the arithmetic to the reader.
// Returns -1 when the date will not parse, which validation has already ruled
// out for the embedded copy.
func (a *Awesome) SyncedAge(now time.Time) int {
	t, err := time.Parse("2006-01-02", a.Synced)
	if err != nil {
		return -1
	}
	d := now.UTC().Truncate(24 * time.Hour).Sub(t)
	return int(d.Hours() / 24)
}
