package registry

import (
	"fmt"
	"regexp"
	"sort"
	"strings"
	"time"
)

// awesome-gno, vendored.
//
// https://github.com/gnoverse/awesome-gno is the community's own answer to
// "what is being built on gno.land", and it holds the half of that answer this
// explorer cannot see: wallets, editors, language servers, SDKs, workshops.
// None of those are a realm, so none of them can ever appear in a chain index.
//
// It is a snapshot in a file rather than a fetch at request time, for the same
// reason the rest of this package is: a page that reads GitHub on every load is
// a page that is down when GitHub is, slow when GitHub is slow, and different
// for two readers a minute apart. The snapshot is generated by
// `make awesome` (cmd/awesome-sync), committed, and embedded at build time, and
// it carries the commit it came from and the day it was taken so the page can
// say how old it is instead of implying it is live.

// AwesomeLink is a link that appeared inside an entry's description, lifted out
// of the markdown. The frontend builds DOM and never interpolates HTML, so a
// description has to arrive as plain text with its links beside it rather than
// as markup the page would have to parse.
type AwesomeLink struct {
	Text string `json:"text"`
	URL  string `json:"url"`
}

// AwesomeEntry is one bullet.
type AwesomeEntry struct {
	Name string `json:"name"`
	URL  string `json:"url,omitempty"`
	// Description is the prose after the dash, with any inline markdown links
	// flattened to their text and collected into Links.
	Description string        `json:"description,omitempty"`
	Links       []AwesomeLink `json:"links,omitempty"`
	// Path is the gno.land realm this entry points at, when one of its links
	// names a realm and nothing but a realm. A link with a render argument
	// (`r/gnoland/blog:p/gno-debugger`) names a *page* of a realm rather than
	// the realm itself, and attributing it to `r/gnoland/blog` would file the
	// Gno debugger under the blog. Those are deliberately left pathless.
	Path string `json:"path,omitempty"`
}

// AwesomeSection is one `##` heading and its bullets.
type AwesomeSection struct {
	Title   string         `json:"title"`
	Slug    string         `json:"slug"`
	Note    string         `json:"note,omitempty"`
	Entries []AwesomeEntry `json:"entries"`
	// Archived says the list itself has retired these entries. Set at load
	// from awesomeArchived rather than stored in the file: it is this repo's
	// reading of somebody else's document, and writing it into the generated
	// snapshot would make it look like the community asserted it.
	Archived bool `json:"archived,omitempty"`
}

// Awesome is the parsed snapshot.
type Awesome struct {
	Source   string           `json:"source"`
	Readme   string           `json:"readme"`
	Contrib  string           `json:"contributing"`
	Commit   string           `json:"commit"`
	Synced   string           `json:"synced"`
	Sections []AwesomeSection `json:"sections"`
}

// Count is how many entries the snapshot holds, across every section.
func (a *Awesome) Count() int {
	n := 0
	for _, s := range a.Sections {
		n += len(s.Entries)
	}
	return n
}

// Paths is every realm this list points at, deduplicated and sorted, which is
// what the API asks the store about.
func (a *Awesome) Paths() []string {
	seen := map[string]bool{}
	out := []string{}
	for _, s := range a.Sections {
		for _, e := range s.Entries {
			if e.Path != "" && !seen[e.Path] {
				seen[e.Path] = true
				out = append(out, e.Path)
			}
		}
	}
	sort.Strings(out)
	return out
}

// awesomeArchived names the sections whose entries are explicitly no longer
// current. The list keeps them, and so do we, but a directory that mixed a
// retired testnet into the same grid as a live app would be worse than one that
// dropped them: the reader cannot tell, and the page is the only thing that
// could have told them.
var awesomeArchived = map[string]bool{"archive": true}

var (
	commitSHA = regexp.MustCompile(`^[0-9a-f]{40}$`)
	slugSafe  = regexp.MustCompile(`^[a-z0-9-]+$`)
)

func loadAwesome() (*Awesome, error) {
	var doc Awesome
	if err := readJSON("data/awesome.json", &doc); err != nil {
		return nil, err
	}
	if err := validateAwesome(&doc); err != nil {
		return nil, err
	}
	for i := range doc.Sections {
		doc.Sections[i].Archived = awesomeArchived[doc.Sections[i].Slug]
	}
	return &doc, nil
}

func validateAwesome(a *Awesome) error {
	switch {
	case strings.TrimSpace(a.Source) == "":
		return fmt.Errorf("awesome.json: no source")
	case !commitSHA.MatchString(a.Commit):
		// The commit is what makes the snapshot checkable: without it a reader
		// cannot tell which version of the list they are looking at, and a
		// regenerated file is indistinguishable from an edited one.
		return fmt.Errorf("awesome.json: commit %q is not a full sha", a.Commit)
	case len(a.Sections) == 0:
		return fmt.Errorf("awesome.json: no sections")
	}
	if err := validateChecked("awesome.json", "snapshot", a.Synced); err != nil {
		return err
	}
	if a.Synced == "" {
		return fmt.Errorf("awesome.json: no synced date")
	}
	seenSlug := map[string]bool{}
	for _, s := range a.Sections {
		switch {
		case strings.TrimSpace(s.Title) == "":
			return fmt.Errorf("awesome.json: a section has no title")
		case !slugSafe.MatchString(s.Slug):
			return fmt.Errorf("awesome.json: %q has slug %q, want [a-z0-9-]+", s.Title, s.Slug)
		case seenSlug[s.Slug]:
			return fmt.Errorf("awesome.json: slug %q is used twice", s.Slug)
		case len(s.Entries) == 0:
			return fmt.Errorf("awesome.json: %q has no entries", s.Title)
		}
		seenSlug[s.Slug] = true
		for _, e := range s.Entries {
			if strings.TrimSpace(e.Name) == "" {
				return fmt.Errorf("awesome.json: %q holds an entry with no name", s.Title)
			}
			if e.Path != "" && !realmPath.MatchString(e.Path) {
				return fmt.Errorf("awesome.json: %s has path %q, which is not a gno.land path", e.Name, e.Path)
			}
			if e.Path != "" && strings.Contains(e.Path, ":") {
				// Belt and braces: the parser already refuses these, and the
				// reason is worth failing loudly on rather than rediscovering.
				return fmt.Errorf("awesome.json: %s has path %q, which names a page and not a realm", e.Name, e.Path)
			}
		}
	}
	return nil
}

// SyncedAge is how many days old the snapshot is, for a page that would rather
// say "14 days ago" than print a date and leave the arithmetic to the reader.
// Returns -1 when the date will not parse, which validation has already ruled
// out for the embedded copy.
func (a *Awesome) SyncedAge(now time.Time) int {
	t, err := time.Parse("2006-01-02", a.Synced)
	if err != nil {
		return -1
	}
	d := now.UTC().Truncate(24 * time.Hour).Sub(t)
	return int(d.Hours() / 24)
}
